services:
  postgres:
    image: postgres:16
    container_name: hizliisler-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hizliisler
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hizliisler" ]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    container_name: hizliisler-api
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./out/sftp:/app/out/sftp
    command: [ "/bin/sh", "./docker/entrypoint.sh" ]

  adminer:
    image: adminer
    container_name: hizliisler-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
