version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: unless-stopped
    ports:
      - "5432:5432" # <<< DEĞİŞTİ: host 5433, container 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123!
      POSTGRES_DB: postgres
    healthcheck:
      # <<< EK: sağlıklı kalktı mı?
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
