services:
  db:
    image: postgres:16
    container_name: hizliisler-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hizliisler
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hizliisler" ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: hizliisler-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hizliisler-api
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./out/sftp:/app/out/sftp
    command: >
      sh -lc "
        npx prisma migrate deploy || npx prisma db push;
        node dist/src/main.js
      "

volumes:
  pgdata:
